## 端口号设置
server:
  port: 8000
## 配置数据源
spring:
  application:
    name: product
  datasource:
    username: root
    password: root
    url: jdbc:log4jdbc:mysql://localhost:5820/supermarket_pms
    ## 可以打印详细sql的驱动
    driver-class-name: net.sf.log4jdbc.DriverSpy
  ##driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 120.79.166.45:1111

## 扫描.xml文件
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
